packages/manager.go, packages/manager_test.go
Hi @bfirsh, 
Thanks for this awesome project. I'm very excited about the whole idea behind it!
This PR fixes an issue related with `list` command when we've folders in the `INSTALL_PATH`.
Let me know if you have any concern about what I did.
=> fixing List command

cmd/install.go
=> Add more context to error message from first run of docker client method

packages/manager.go, packages/manager_test.go
=> Fix permission denied

client/client.go, cmd/install.go, cmd/search.go
=> Use older Engine API version for compatibility

.codeclimate.yml
Adding a Code Climate config with gofmt and golint.
@bfirsh
=> Adding Code Climate config

cmd/install.go, packages/package.go, packages/package_test.go
=> Ask permission from user to mount volumes and pass environment variables

cmd/install.go
Useful for non-interactive installs
=> added -y (assume yes) to the install command

README.md, go.mod, go.sum, packages/package.go, packages/package_test.go, packages/resources/aws, packages/resources/aws-incompatible, packages/resources/syntax-error, version/version.go, version/version_internal_test.go
This label must provide a semver expression of the version compatibility
fixes: #35
=> Add label to specify required whalebrew version

README.md
This PR updates installation instructions in README.md to use Homebrew.
/ref #33
=> Update installation instructions to use Homebrew

cmd/search.go
Unfortunately it seems that docker search has been updated making it
impossible to search over specific repository
```
$ docker search whalebrew
NAME                              DESCRIPTION                                     STARS               OFFICIAL            AUTOMATED
whalebrew/youtube-dl                                                              2
whalebrew/wget                                                                    1
whalebrew/speedtest                                                               1
ordnancesurvey/whalebrew-mbutil   Whalebrew image for MBUtil - a utility for i…   0                                       [OK]
whalebrew/awscli                                                                  0
whalebrew/nkf …
```
=> Move search to use hub API

cmd/search.go
=> Fix search panic when run without arguments

packages/package.go, packages/package_test.go
buildkit built images are not providing the ContainerConfig we are
reading labels from. Instead, everything is populated in the Config field
of `inspect`.
We should eventually have better visibility about those fields in this
issue: https://github.com/docker/cli/issues/2868
Meanwhile, we should support it the best way possible.
Benefit from having to do this change to mutualise the label parsing
logic so we are consistent in how we manage the label lookup and
encoding (prefer yaml and fallback to string when possible)
Fixes: #119
=> Support images built with buildkit

CHANGELOG.md, README.md
* Whalebrew search without pattern was wrongly claiming to list all available packages (#133)
* Images were wrongly run with TTY in case commands were piped (#136)
* Add a linter to validate image labels (#126)
=> Create release 0.3.0

.github/workflows/go.yml, go.mod, go.sum
<details>
<summary>
</summary>
</details>
=> Bump go version to 1.17.5

go.mod, go.sum
<details>
<summary>
</summary>
</details>
=> bump github.com/Songmu/prompter to v0.5.0

go.mod, go.sum, version/version.go, version/version_internal_test.go
<details>
<summary>
</summary>
</details>
=> bump semver to v4

config/config.go, go.mod, packages/manager.go, packages/package.go
<details>
<summary>
</summary>
</details>
=> bump gopkg.in/yaml to v3

CHANGELOG.md, README.md
<details>
<summary>
</summary>
Local-Branch: master
</details>
=> Create release 0.4.0

search/dockerhub.go
<details>
<summary>
</summary>
</details>
=> Fix docker hub interface breaking change

.github/workflows/go.yml, go.mod
Change-Id: I17488f6e6f3ac3fcb3dfc2b06f8480e87c99c3c3
=> Bump go version to 1.20

.github/workflows/go.yml
Provide the actual build date, sha and run number in the whalebrew version
Change-Id: I975dbdb0ae7fc19e01ef7f95e66bdab37652ef8f
=> Increase traceability of build version

.github/dependabot.yml
Change-Id: I95d7ae31aab79735fb654be170969e989c9fec68
=> Add dependabot for remaining dependencies

.github/workflows/approve.yaml
Change-Id: I007be45427c6f3219732e2dd6314704d161640bd
=> Add auto approve for trusted users

CHANGELOG.md
Change-Id: Ibd10d680aa274d35166896b09717528332798c93
=> Label latest PRs in CHANGELOG.md

README.md
SMall change, but I updated Docker for Mac details to Docker Desktop
=> Update README to use new Docker name and link

.github/workflows/go.yml, .github/workflows/release.yaml, Dockerfile, actions/release/Dockerfile, actions/release/action.yml, actions/release/go.mod, actions/release/go.sum, actions/release/main.go, actions/release/main_test.go
We have to rollback the artifacts management upgrade because of this
issue:
https://github.com/actions/upload-artifact/issues/478
<details>
<summary>
</summary>
</details>
=> Automate release through github actions
