whalebrew/whalebrew

README.md
cmd/run.go
packages/manager.go
packages/manager_test.go

This project is awesome! Been working a little on something like it but not in a generalized way so thanks!
I thought it'd be nice to add port mappings. This is a pretty simple version of it but its a start.
Usage would be:
```
LABEL io.whalebrew.config.ports '["8100:8100"]'
```

Port mapping

---

version/version.go

`version.Version` should not be mutable during execution, so make it immutable.

Make `version.Version` immutable

---

packages/manager.go

The `path` variable has a same name of the imported `path` package and it shadows the reference to the `path` package accidentally. To avoid this kind of shadowing, the `path` variable is renamed to `p`.

Rename the `path` variable

---

cmd/edit.go

Add edit command. This way it is easy to modify executable right from the command line i.e. `whalebrew edit whalesay` opens system EDITOR with `<install_path>/whalesay` to be easily edited.
What do you think? I was looking for an easy and quick way to change ports.

Add cmd/edit.go

---

cmd/run.go

Set the uid and primary gid as the user executing the command.
For example, if the "ubuntu" user is a member of the docker group, then the permissions one might expect with "whalebrew/wget" might be ubuntu:ubuntu rather than root:root.
```terminal
ubuntu@ip-172-37-43-241:~/$ wget https://www.google.com/favicon.ico
ubuntu@ip-172-37-43-241:~/$ ls -al
-rw-r--r-- 1 ubuntu ubuntu     5430 Dec  8 01:00 favicon.ico
```
Related issues: https://github.com/bfirsh/whalebrew/issues/11, https://github.com/bfirsh/whalebrew/issues/40

use executor file permissions

---

cmd/install.go
packages/manager.go
packages/manager_test.go
script/build

While developing a package I was switching between a local docker image and production image, which meant I was repeatedly uninstalling (which prompts for input) and installing. I added force install flag to support installing regardless whether the package is installed or not.

Added force install support

---

README.md
cmd/run.go
packages/package.go

I like the idea of being able to run a command with a working directory matching the host current directory (thinking of copy pasting error messages for debug)
This PR adds this feature as well as providing a convenient way to derive environment variables and volumes from user's environment

Use customizable working directory

---

client/client.go

The latest docker client interface does not have any UpdateClientVersion any longer since https://github.com/moby/moby/commit/5f1d94e569592fc2680f8661e16d0e5b02e82492

Update client creation interface.

---

cmd/run.go

With this PR, whalebrew package container will be run with `--init` option of `docker run` command.
/close #71 
---
whalebrew run command does not use --init option of docker run command
for running packages. Due to this, some packages need tiny init such as
dumb-init.

Run package container with --init option

---

README.md
cmd/install.go
cmd/root.go
cmd/uninstall.go
hooks/hooks.go
hooks/hooks_test.go

As discussed in #59, users may need to add custom behaviours on specific actions (commit the yaml file, validate the image, ...)
This PR adds support for such feature, allowing users to hook into the installation and removal process to provide value they need

Add support for pre/post install hooks

---

README.md
cmd/run.go
packages/package.go

Some images are built to be used with a specific user ID, leave the opportunity to keep this user ID when running the container.
Under mac OS, or when user [remap](https://docs.docker.com/v17.09/engine/security/userns-remap/) is enabled, user keeps benefitting the full access of newly created files.
This option is disabled by default

Add configuration to keep container user

---

cmd/run.go
cmd/run_test.go
main.go

As detailed in #66, run subcommand is an internal command that is
"not designed to be used by a user"
Remove the run command hack to inject an sub command and stop exposing
the internal sub command to the user
fixes: #63

Remove the run subcommand

---

Dockerfile
script/run
script/test

Rework Dockerfile to provide a minimal image.
This image can then easily be ran through
`docker run --rm -v<PathToExecutable>:/executable -v /var/run/docker.sock:/var/run/docker.sock whalebrew/whalebrew /executable <args>`
fixes #32
A step forward for #36

Improve dockerfile

---

README.md
cmd/run.go
cmd/run_internal_test.go
packages/package.go
packages/package_test.go

Change the default behaviour to raise an error when a volume to bind is
missing.
fixes: #38
Other supported behaviours:
- skip (the container will not have the given path mounted)
- mount (the volume will be created by docker as a directory, owned by
root)

Add support to handle missing volumes in custom ways

---

cmd/install.go
cmd/run.go
packages/package.go

This PR implements the same as #66 with the difference that the entry point is only stored in the package file and can be defined at install time.
Unlike #66 this PR does not allow customisation at the run time, being an internal and undocumented feature
Eventually, this could open the opportunity to add "additional commands" in a given package like `io.whalebrew.additional_packages: {"other-command": ["ls", "-al"]}`

Add support for custom entrypoint

---

packages/package.go
packages/package_test.go

When using a custom registry, the image name is often of "registry.io/org/image"
The previous implementation was splitting on / to compute the path of
the executable to dump and hence was trying to create ${WHALEBREW_INSTALL_PATH}/org/image
the org directory being more likely to not exist, and be outside of
$PATH
This implementation considers the image name as a full path and gets
"image" as executable name, installing it to ${WHALEBREW_INSTALL_PATH}/image

Fix invalid name when using a custom registry

---

README.md

This PR updates version number in installation instructions in README.md. It should be updated automatically, but I update it with manual for now.
/ref #33

Update version number in installation instructions

---

cmd/install.go

From the docker inspect, ContainerConfig contains the configuration the the latest step of the docker build.
This means the entrypoint is only considered then it is the last step of the docker build.
However, the Config field contains the actual image configuration and the correct entrypoint regardless the position of the entrypoint
a Dockerfile of
```
FROM alpine
ENTRYPOINT ["sh"]
RUN echo hello world
```
gets a ContainerConfig of
```
"ContainerConfig": {
"Hostname": "",
"Domainname": "",
"User": "",
"AttachStdin": false,
"AttachStdout": false,
"AttachStderr": false,
"Tty": false,
"OpenStdin": false,
"StdinOnce": false,
"Env": [
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
],
"Cmd": [
"/bin/sh",
"-c",
"echo hello world"
],
"ArgsEscaped": true,
"Image": …
```

Fix pkg not installable when entrypoint is not the last step

---

.travis.yml
client/client.go
cmd/install.go
go.mod
packages/manager.go
packages/package.go
packages/package_diff.go
packages/package_test.go

This pr addresses a portion of #17 . It prompts the user to ask if they would like to overwrite their existing installation of a package with a new image. This was already possible via a forced installation but this wasn't evident to me at first at least.

 Ask if a different version of a pkg should be installed when theres an existing installation

---

.gitignore
go.mod
go.sum
main_test.go

Those tests ensures the basic operations works as expected:
- install should create the yaml in the directory
- run should execute the program with current directory binding and get
the output

Add integration tests for main

---

cmd/run.go
cmd/run_internal_test.go
cmd/run_test.go
main.go
packages/resources/aws
run/docker.go
run/docker_test.go
run/interface.go

Splitting the logic between extraction of current execution settings and actual runtime calls
This allows better testability as well as separation of concerns.
It also allows to have different implementations of the pure run interface allowing to support different runtimes whenever.

Extract run to a separate package

---

README.md
cmd/run.go
cmd/run_internal_test.go
go.mod
packages/package.go
packages/package_test.go

When providing filepath on the commandline like `$ wget -O
../google.html https://www.google.com` the destination path is not bound
in the current and hence the user does not see the output file.
With the proposed implementation, the package provider should provide
flags that should contain path to files. Then, whalebrew will parse
those flags and extract volume names from it, instructing to bind those
inside the container.
There is no message added at the install time. Rationale is that the
user provides the paths himself, and hence he expects the path to be
bound. Unlike volumes that are bundled inside the image package.
I am foreseeing few issues to be addressed:
- in case a path is a file it might happen that the output is actually
not flushed inside the host. It has been tested on …

Add an option to mount paths provided in flags

---

cmd/list.go

Updates the `list` command to allow controlling the output of the table
header which is useful for automated CLI interactions and scripts.

cmd/list: Control header output

---

cmd/uninstall.go

Homebrew does not have a guard for uninstalling packages and neither should this package.
I rebuild the package locally and achieved the desired result.
```
whalebrew ❯ go build                                                                                                                                                                                 master
go: downloading github.com/spf13/viper v1.3.2
go: downloading github.com/spf13/cobra v0.0.4-0.20190321000552-67fc4837d267
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/google/go-cmp v0.3.0
go: downloading github.com/docker/docker v0.7.3-0.20190409075915-9d850cbfa5e9
go: downloading golang.org/x/crypto v0.0.0-20190404164418-38d8ce5564a5
go: downloading github.com/spf13/pflag v1.0.3
go: downloading …
```

Removal of the prompt for the uninstall cmd

---

README.md
cmd/search.go
config/config.go

Up until now, whalebrew restricts its searches to https://hub.docker.com/u/whalebrew
This commit introduces the ability to customize search organization under docker hub.
To customize it, place a file like
```
repositories:
- url: https://hub.docker.com
owner: whalebrew
```
You can add as many search repositories as desired, all of them will be searched.
Currently, there is no authentication to the search repositories. Only public images will be retrieved.
A step forward for whaleebrew tap discussed in #102

Add support for multiple search repositories

---

cmd/install.go

Currently the only way around this is to create yaml file manually.

Allow images without entrypoint with -e

---

README.md

The `missing_volumes` example in the README was failing silently.
I didn't open an issue about this, but I'm opening one about silent failures.
EDIT:
Enhancement issue about validating labels: https://github.com/whalebrew/whalebrew/issues/125

Fix missing_volumes example.

---

cmd/install.go
cmd/lint.go
packages/package.go
packages/package_test.go

In order to add a package linter, add a custom structure tag and benefit from it to parse the image labels.
This allows to mutualize the source of truth for the label to field mapping and offers a  way to create linting without having to duplicate the labels mapping.
fixes: #125

Introduce package linter

---

cmd/search.go

As reported by #132, the search command help instructs that searching
without term lists all available packages.
Adjust the search help to remove this statement.

Update the search command help

---

cmd/run.go

As raised in #134, in case of piping whalebrew to a non-tty host native
program, if the original stdin is a TTY, the "whalebrewed" program may
consider being run in a TTY environment and hence send control
characters.
This is the case for `aws logs describe-log-groups` for example.
In the current version of whalebrew, running `aws logs
describe-log-groups | less` (given that less is not running on
whalebrew) results in control characters injected and hence jq to fail
parsing the output json. as described in this stackoverflow discussion
https://stackoverflow.com/questions/65824304/aws-cli-returns-json-with-control-codes-making-jq-fail
This problem can be easily solved by setting the TTY flag only when both
input and output are TTYs.
The case could still happen if the final less is also …

Don't run as TTY when stdout is not a TTY

---

cmd/uninstall.go
packages/manager.go
packages/manager_test.go
packages/package.go

While the install commands accepts an image name, the uninstall command
expects the package name.
This is confusing for users as the command is not symetrical.
Implement a simple detection mechanism that allows to detect the
relevant package to be deleted so the uninstall command can be used
using the image name as the install endpoint accepts. The previous
behaviour to be able to uninstall a package from its name is kept
fixes #162
<details>
<summary>
</summary>
Local-Branch: master
</details>

Detect package or image name in uninstall

---

README.md

This should make it easier to install Docker on macOS.

README: add `brew install --cask docker`

---

CHANGELOG.md
cmd/install.go
config/config.go
config/config_internal_arm64_darwin_test.go
config/config_internal_other_platforms_test.go
config/config_internal_test.go
config/config_test.go

Follow the path drawn by homebrew and use a dedicated path on arm64 with mac os: https://github.com/Homebrew/brew/blob/b855a9eae8b7daf5fa7fbe4acc111c57024c2307/docs/FAQ.md#why-is-the-default-installation-prefix-opthomebrew-on-apple-silicon
This creates an additional requirement where users will need to manually create this path for the moment.
This will be addressed in different PR to come
fixes: #191
Change-Id: Ida3629f985608680abad2402d5f9c20a2dd7835c

Move default installation to /opt/whalebrew/bin on mac arm64

---

CHANGELOG.md
cmd/install.go

As we have moved, on darwin arm64, the default installation path outside from the relatively standard /usr/local/bin that was also used by homebrew, it is likely that the installation directory is not included in the PATH lookup and hence breaks the installation for several users.
Detect this situation and invite the users to take action and add the installPath in their PATH
Change-Id: I1ff03150f253ef998ce9f04c2f2d35552b1d6629

Add a warning when installDir is not in PATH

---

CHANGELOG.md
cmd/install.go

As we have moved, on darwin arm64, the default installation path outside from the relatively standard /usr/local/bin that was also used by homebrew, it is likely that the installation directory does not exist.
When this is the case, try to create it and fallback using sudo as `/opt` is owned by root on darwin arm64, preventing any user to create sub-folders there.
Change-Id: Ide5b46c060d99cd9a424d63fc2ef98938a079292

Automatically try to create installation path if it does not exist
